### PR TITLE
inline documentation

### PR DESCRIPTION
**Pull request by abhijithch**
Included inline documentation for some of the exposed functions.

### CODE REVIEW

**Comment by ViralBShah** [comment]
We need to tag a new release.

**Comment by tkelman** [comment]
Do we really need package documentation for methods that are exactly the same signatures as in base?

**Comment by ViralBShah** [comment]
Why not? Question is if it should just point to Base, but I suspect that this will have other notes that will have to come in from Yeppp.

**Comment by tkelman** [comment]
Because the base versions of these methods are probably documented more clearly? If these are following the same API that is not specific to yeppp in any way, there's nothing to be gained by putting these here. Yeppp specific documentation can be added of course, or anywhere the corresponding base docstring is missing it can be added there.

**Comment by abhijithch** [comment]
@tkelman we did'nt want to not have any helper functions for Yeppp. So what would the best way to point it to base where the APIs are the same?

**Comment by tkelman** [comment]
Ah sorry my mistake, I didn't realize that this module isn't extending anything from base, it has its own separate `Yeppp.dot` etc methods. This is fine for now then.

**Pull request merged**
